apiVersion: v1
kind: Service
metadata:
  labels:
    app: "${REDIS_SERVICE_NAME}-redis-sentinel"
    name: sentinel
    role: service
  name: "${REDIS_SERVICE_NAME}-redis-sentinel"
spec:
  ports:
    - port: 26379
      targetPort: 26379
  selector:
    redis-sentinel: "true"
