apiVersion: v1
kind: DeploymentConfig
metadata:
  labels:
    app: "${REDIS_SERVICE_NAME}-redis"
  name: "${REDIS_SERVICE_NAME}-redis"
spec:
  replicas: 3
  selector:
    app: "${REDIS_SERVICE_NAME}-redis"
  strategy:
    rollingParams:
      intervalSeconds: 1
      maxSurge: 25%
      maxUnavailable: 25%
      timeoutSeconds: 600
      updatePeriodSeconds: 1
    type: Rolling
  template:
    metadata:
      labels:
        app: "${REDIS_SERVICE_NAME}-redis"
    spec:
      containers:
        - name: redis
          image: redis:v1.0.0
          imagePullPolicy: Always
          ports:
            - containerPort: 6379
              protocol: TCP
          env:
            - name: REDIS_SENTINEL_SERVICE_HOST
              value: "${REDIS_SERVICE_NAME}-redis-sentinel.${NAMESPACE}.svc"
            - name: REDIS_SENTINEL_SERVICE_PORT
              value: "26379"
          resources:
            limits:
              memory: "${MEMORY_LIMIT}"
          terminationMessagePath: /dev/termination-log
          volumeMounts:
            - mountPath: /redis-master-data
              name: data
      volumes:
        - emptyDir: {}
          name: data
